version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"

    # Automerge all development updates and production
    # security (semver patch) updates (waiting for CI to pass)
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "security:patch"
